# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    env: 
      CI: false
    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    # - run: git clone https://github.com/Vanej88/Vanej88.github.io.git demo
    # - run: cp -r demo/* .
    # - run: rm -rf demo

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: 82.223.104.170
        username: ${{secrets.USER}}
        password: ${{secrets.PASS}}
        port: 22
        script: rm -rf /var/www/html
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: 82.223.104.170
        username: ${{secrets.USER}}
        password: ${{secrets.PASS}}
        port: 22
        source: "build/*"
        target: "/var/www/html"
    - name: move files
      uses: appleboy/ssh-action@master
      with:
        host: 82.223.104.170
        username: ${{secrets.USER}}
        password: ${{secrets.PASS}}
        port: 22
        script: cp -r /var/www/html/build/* /var/www/html/